version: '2.1'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "2"


services:
  velocity-router:
    image: nginx:1.14
    logging: *default-logging
    volumes:
     - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf.template
     - ./conf/ssl/server.crt:/etc/nginx/ssl/server.crt
     - ./conf/ssl/server.key:/etc/nginx/ssl/server.key
    ports:
      - "${NGINX_PORT_EXPOSED}:${NGINX_PORT}"
    environment:
      - NGINX_PROTOCOL=${NGINX_PROTOCOL}
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
    command: /bin/bash -c "envsubst '$${NGINX_PROTOCOL},$${NGINX_HOST},$${NGINX_PORT}' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -c /etc/nginx/conf.d/nginx.conf -g 'daemon off;'"
    links:
      - release-events-ui
      - release-events-api
      - security-api
      - continuous-release-ui
      - multi-app-pipeline-api
      - application-api
      - continuous-release-consumer
      - reporting-sync-api
      - reporting-consumer

  database:
    image:  mongo:3.4
    logging: *default-logging
    command: mongod --quiet --logpath=/dev/null
    volumes:
      - mongodb:/data/db

  reporting-ui:
    image: ${DOCKER_REGISTRY_PREFIX}reporting-ui:1.0.74
    logging: *default-logging
    depends_on:
      security-api:
        condition: service_healthy
    links:
      - database
    environment:
      - ROOT_URL=${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}/reports
      - APP_HOME=${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}
      - DDP_DEFAULT_CONNECTION_URL=${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}/reports
      - PORT=80
      - MONGO_URL=mongodb://database:27017/reporting
      - ENCRYPT_KEY=${CIPHER_KEY}
      - ADMIN_PASSWORD=admin
      - DISABLE_SSL=true
      - COMPOSE_VERSION=1.0.0
      - LOG_LEVEL=${LOG_LEVEL}
      - JWT_HMAC_KEY=${HMAC_KEY}
      - SECURITY_AUTH_URL=${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}/security-api/auth
      - SECURITY_API_AUTH_TOKEN=${API_TOKEN}
      - VELOCITY_VERSION=1.1.2

  reporting-consumer:
    image: ${DOCKER_REGISTRY_PREFIX}reporting-consumer:1.0.59
    logging: *default-logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6004/ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    links:
      - database
    environment:
      - MONGO_URL=mongodb://database:27017/reporting
      - ENCRYPT_KEY=${CIPHER_KEY}
      - CONSUMER_URL=${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}/reporting-consumer
      - BEARER_TOKEN=${API_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL}
      - AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitnode1:5672/
      - NODE_TLS_REJECT_UNAUTHORIZED=0

  continuous-release-consumer:
    image: ${DOCKER_REGISTRY_PREFIX}continuous-release-consumer:1.0.167
    logging: *default-logging
    links:
      - rabbitnode1
    environment:
      - NODE_ENV=onprem
      - PORT=3411
      - API_TOKEN=${API_TOKEN}
      - CIPHER_KEY=${CIPHER_KEY}
      - HMAC_KEY=${HMAC_KEY}
      - AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitnode1:5672/

  reporting-sync-api:
    image: ${DOCKER_REGISTRY_PREFIX}reporting-sync-api:1.0.28
    logging: *default-logging
    links:
      - rabbitnode1
    environment:
      - NODE_ENV=onprem
      - PORT=3499
      - BEARER_TOKEN=${API_TOKEN}
      - AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitnode1:5672/

  application-api:
    image: ${DOCKER_REGISTRY_PREFIX}application-api:1.0.349
    logging: *default-logging
    links:
      - database
      - security-api
    environment:
      - DB_TYPE=mongo
      - MONGO_URL=mongodb://database:27017
      - MONGO_DB=application-api
      - NODE_ENV=onprem
      - PORT=3499
      - BEARER_TOKEN=${API_TOKEN}
      - SECURITY_API_URL=http://security-api:3911
      - SECURITY_API_AUTH_TOKEN=${API_TOKEN}

  release-events-ui:
    image: ${DOCKER_REGISTRY_PREFIX}release-events-ui:1.0.240
    logging: *default-logging
    depends_on:
      release-events-api:
        condition: service_started
    environment:
      - NODE_ENV=production
      - PORT=3010
      - LOG_LEVEL=${LOG_LEVEL}
      - release_events_api__host=${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}/release-events-api
      - security_api__host=${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}/security-api
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - version=1.1.2

  release-events-api:
    image: ${DOCKER_REGISTRY_PREFIX}release-events-api:1.0.212
    logging: *default-logging
    depends_on:
      security-api:
        condition: service_healthy
      multi-app-pipeline-api:
        condition: service_healthy
      reporting-consumer:
        condition: service_healthy
    links:
      - database
      - rabbitnode1
      - continuous-release-ui
      - security-api
      - reporting-consumer
    environment:
      - PORT=8080
      - MONGO_DB=release-events
      - LOG_LEVEL=${LOG_LEVEL}
      - MONGO_URL=mongodb://database:27017
      - SECURITY_API_URL=http://security-api:3911
      - SECURITY_API_AUTH_TOKEN=${API_TOKEN}
      - JWT_CIPHER_KEY=${CIPHER_KEY}
      - JWT_HMAC_KEY=${HMAC_KEY}
      - DEPLOY_PLAN_API_URL=http://continuous-release-ui/deploymentPlans
      - DEPLOY_PLAN_API_CIPHER_KEY=${CIPHER_KEY}
      - DEPLOY_PLAN_API_HMAC_KEY=${HMAC_KEY}
      - BEARER_TOKEN=${API_TOKEN}
      - AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitnode1:5672/
      - MAP_API_URL=http://multi-app-pipeline-api:9090
      - MAP_API_PATH=${MAP_API_PATH}
      - MAP_API_TOKEN=${API_TOKEN}
      - REPORTING_CONSUMER_API_URL=http://reporting-consumer:6004
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - REPORTING_UI_URL=http://reporting-ui/reports
      - APP_API_URL=http://application-api:3499

  security-api:
    image: ${DOCKER_REGISTRY_PREFIX}security-api:1.0.82
    logging: *default-logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3911/api/v1/status"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      - rcl-web-client
    links:
      - database
      - rcl-web-client
    environment:
      - NODE_ENV=local
      - PORT=3911
      - LOG_LEVEL=${LOG_LEVEL}
      - MONGO_URL=mongodb://database:27017/security
      - MONGO_DB=security
      - TIAM_CLIENT_SECRET=72heYpy2weRih8I3KTxdMVOy90bBpQB0WDY3fH2IixOaAtwnRU
      - BEARER_TOKEN=${API_TOKEN}
      - SECURITY_AUTH_SECRET=${HMAC_KEY}
      - LOGICAL_APP_NAME=security-api
      - BUILD_PREFIX=master
      - JWT_CIPHER_KEY=${CIPHER_KEY}
      - JWT_HMAC_KEY=${HMAC_KEY}
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - ACCESS_KEY=${ACCESS_KEY}
      - RCL_WEB_CLIENT_URL=http://rcl-web-client:4567
      - AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitnode1:5672/

  continuous-release-ui:
    image: ${DOCKER_REGISTRY_PREFIX}continuous-release-ui:1.0.163
    logging: *default-logging
    depends_on:
      security-api:
        condition: service_healthy
    links:
      - database
      - rabbitnode1
    environment:
      - PORT=80
      - ROOT_URL=${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}/deploymentPlans
      - MONGO_URL=mongodb://database:27017/velocity
      - LOG_LEVEL=${LOG_LEVEL}
      - AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitnode1:5672/
      - APP_API_URL=http://application-api:3499
      - APP_API_AUTH_TOKEN=${API_TOKEN}
      - SECURITY_API_URL=http://security-api:3911/api
      - SECURITY_API_AUTH_TOKEN=${API_TOKEN}
      - REPORTING_CONSUMER_API_URL=http://reporting-consumer:6004
      - REPORTING_CONSUMER_API_AUTH_TOKEN=${API_TOKEN}
      - RELEASE_API_URL=http://release-events-api:8080/graphql
      - RELEASE_API_AUTH_TOKEN=${API_TOKEN}
      - MAP_API_URL=http://multi-app-pipeline-api:9090${MAP_API_PATH}/graphql
      - MAP_API_AUTH_TOKEN=${API_TOKEN}
      - JWT_HMAC_KEY=${HMAC_KEY}
      - CR_CIPHER_KEY=${CIPHER_KEY}
      - CR_HMAC_KEY=${HMAC_KEY}
      - CONNECT_URL=http://reporting-consumer:6004
      - CONNECT_TOKEN=${API_TOKEN}
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - AUTH_TOKEN_URL=https://login.ng.bluemix.net/UAALoginServerWAR/oauth/token
      - DRA_API_URL=https://dra.ng.bluemix.net
      - TOOL_CHAINS_URL=https://devops-api.ng.bluemix.net
      - DEVOPS_MESSAGE_STORE_API=https://dlms.ng.bluemix.net
      - |
        METEOR_SETTINGS=
        {
          "public": {
            "requireAuth": true,
            "securityAuthUrl": "${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}/security-api/auth",
            "version": "1.1.2",
            "features": {
              "SlackTask": false,
              "PipelineV2Task": false,
              "EmailNotifications": true,
              "EmailTask": true,
              "RunAnotherPlanTask": true,
              "Approvals": true,
              "ApprovalTask": true,
              "ServiceNowTask": true,
              "JenkinsTask": true
            }
          }
        }

  rabbitnode1:
    image: 'rabbitmq:3.6-management'
    logging: *default-logging
    environment:
      - RABBITMQ_ERLANG_COOKIE='128ad9b8-3d9f-11e8-b467-0ed5f89f718c'
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_DEFAULT_VHOST=/
    hostname: rabbitnode1
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 10
    #NOTE Expose ports only for access from outside the cluster.
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbit1:/var/lib/rabbitmq
      - ./conf/rabbit:/etc/rabbitmq/
    command:  bash -c 'sleep 10; rabbitmq-server;'

  multi-app-pipeline-api:
    image: ${DOCKER_REGISTRY_PREFIX}multi-app-pipeline-api:1.0.105
    logging: *default-logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/v1/multi-app-pipeline/status"]
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      security-api:
        condition: service_healthy
    links:
      - database
      - security-api
      - continuous-release-ui
    environment:
      - NODE_ENV=container
      - PORT=9090
      - mongo__url=mongodb://database:27017
      - mongo__db=multi-app-pipeline
      - appPath=${MAP_API_PATH}
      - authToken=${API_TOKEN}
      - securityApi__url=http://security-api:3911
      - securityApi__auth_secret=${HMAC_KEY}
      - deployPlanApi__url=http://continuous-release-ui/deploymentPlans
      - deployPlanApi__cipherKey=${CIPHER_KEY}
      - deployPlanApi__hmacKey=${HMAC_KEY}
      - applicationApi__url=http://application-api:3499
      - bearerToken=${API_TOKEN}
      - cipher__key=${CIPHER_KEY}
      - hmac__key=${HMAC_KEY}
      - registrationApi__token=${API_TOKEN}
      - integrationApi__token=${API_TOKEN}
      - pipelineApi__cipherKey=${CIPHER_KEY}
      - pipelineApi__hmacKey=${HMAC_KEY}
      - releaseEventsApi__cipherKey=${CIPHER_KEY}
      - releaseEventsApi__hmacKey=${HMAC_KEY}
      - releaseEventsApi__url=http://release-events-api:8080/graphql
      - amqp__velocity__url=amqp://rabbitnode1:5672/
      - amqp__velocity__password=${RABBITMQ_PASS}
      - amqp__velocity__user=${RABBITMQ_USER}
      - newRelic__enabled=false
      - redis__enabled=false
      - tunnel__enabled=false
      - serviceProvider__credentials=Y29udF9yZWxlYXNlX3N2Yzp0cDRNQk53TU0y
      - NODE_TLS_REJECT_UNAUTHORIZED=0

  continuous-release-poller:
    image: ${DOCKER_REGISTRY_PREFIX}continuous-release-poller:1.0.15
    logging: *default-logging
    links:
      - application-api
    environment:
      - MONGO_URL=mongodb://database:27017/velocity
      - APP_API_TOKEN=${API_TOKEN}
      - APP_API_URL=http://application-api:3499
      - NODE_ENV=prod
      - AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitnode1:5672/

  rcl-web-client:
    image: ${DOCKER_REGISTRY_PREFIX}rcl-web-client:1.0.40
    logging: *default-logging

volumes:
  mongodb:
    driver: local
  rabbit1:
    driver: local
